### ISSUE TITLE
scaffolding/notty_cairo/notty incorrect scrolling behavior

### ISSUE THREAD

**Issue by waynr** [withoutboats/notty#15]
When the terminal contents exceed the size of the scaffolding window they appear to continue downward in the undisplayed portion of the drawing area rather than pushing old terminal contents above the displayed portion of the drawing area to make room for new stuff as I have come to expect of terminal emulators.

**Comment by withoutboats** [comment]
Yeah scrolling is in a bit of a limbo right now. The way it used to work was that `notty-cairo` would keep track of its scroll position and draw a section of the grid, but that's not adequate. The multigrid PR (#9) will solve this issue, because scrolling will be a property of individual grids built into the core state machine.

The issue then will be implementing scrolling back with scroll bars and things.
